# Generated by Django 4.2.7 on 2023-12-23 09:40

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(default=0)),
                ("url", models.URLField(max_length=1000)),
                ("ip_address", models.GenericIPAddressField()),
                ("http_header", models.CharField(default="", max_length=1000)),
                ("user_agent_header", models.CharField(max_length=1000)),
                ("window_width", models.IntegerField(default=0)),
                ("window_height", models.IntegerField(default=0)),
                ("max_touch_points", models.IntegerField(default=0)),
                ("language", models.CharField(max_length=30)),
                ("time", models.DateTimeField(default="2023-12-23 10:40:31")),
                ("domain", models.CharField(default="", max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="EmailUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.EmailField(default="", max_length=254, unique=True),
                ),
                ("url", models.URLField(default="", max_length=1000)),
                ("domain", models.CharField(default="", max_length=1000)),
                (
                    "groups",
                    models.ManyToManyField(related_name="email_users", to="auth.group"),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="email_users", to="auth.permission"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
