# Generated by Django 4.2.7 on 2023-12-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_and_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteinfo",
            name="time",
            field=models.DateTimeField(default="2023-12-23 10:49:25"),
        ),
    ]
