# Generated by Django 4.2.7 on 2023-12-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_and_tracking", "0002_alter_siteinfo_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteinfo",
            name="time",
            field=models.DateTimeField(default="2023-12-23 18:48:29"),
        ),
    ]
