POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{"username":"test103@o2.pl","url":"https://test85driven.io/blog/django-custom-user-model/"}

###

POST http://127.0.0.1:8000/site_info/
Content-Type: application/json
Authentication: dd87c375adf0bf306c6b61c40bcce03340d8ed33
{"url":"https://test85driven.io/blog/django-custom-user-model/","ip_address":"8.8.8.8","http_header":"siemanskd23","user_agent_header":"alalalala","window_width":23,"window_height":25,"max_touch_points":32,"language":"polski"}